### ISSUE TITLE
Fluids give errors if used in Mine/Modtweaker functions

### ISSUE THREAD

**Issue by Yulife** [0tho/CustomItems#18]
When I generated a list of unlocalized names of fluids with /mt liquids the Minetweaker log gave me [this](http://paste.ee/p/cxzM1) unlocalized name. However, when I used the unlocalized name in a Modtweaker script that goes like this "mods.tconstruct.Smeltery.addMelting(<Steamcraft:steamcraftOre:1>, <liquid:molten zinc> * 288, 400, <Steamcraft:steamcraftOre:1>);" it gives me a [giant error](http://paste.ee/p/7qSqB).

I am running the latest Forge, Minetweaker and CustomItems.

EDIT: Changing the name of the fluid to "MoltenZinc" in the json fixed it, however, it is not a good workaround. The localized name have no backspace which is rather weird.

**Comment by 0tho** [comment]
I am not very familiar with liquids in MT. If you could, please send me the configs needed to this error, so I can test it more easily

**Comment by Yulife** [comment]
[JSON](http://paste.ee/p/ZqlxO)
[Minetweaker script](http://paste.ee/p/lKsWk)
My suggestion is that you remove the backspace from the unlocalized name every time a fluid is created. However, I am not a coder so it may not be so easy :P

**Comment by 0tho** [comment]
I made a small change to how fluids are named. It should be fixed.
