### ISSUE TITLE
Light & Render issue 

### ISSUE THREAD

**Issue by Cyd007** [0tho/CustomItems#20]
For custom stairs, it seem that there are some lighting issues when blocks are right next to the stair steps as well ass shadow casting. The following link is some example with the default stair block. 

https://www.dropbox.com/sh/pt5wrtrtd5pgwe6/AABT4RiqhQ8Cn4Ue020YzkgCa?dl=0

For custom slabs, there is a render issue on the side where the two custom slabs are staggered. However when a custom slab is placed next to a double stacked slab it is fine. The following link will give a better demonstration of the problem. 

https://www.dropbox.com/sh/rau75iknnl2ukur/AACvNdqM9VpbiRhl15qNIox6a?dl=0

**Comment by 0tho** [comment]
Thx for the report Cyd. It has been fixed
