### ISSUE TITLE
Walls duplicate issue

### ISSUE THREAD

**Issue by Cyd007** [0tho/CustomItems#22]
I have notice was a duplicate version of a wall. For an example, in vanilla Minecraft there is two versions of a cobble wall. A normal cobble wall and a mossy cobble wall. When a custom wall is created, there is a second version or a duplicate like I mentioned previously. I don't know if it was intended or am mistake just thought you aught to know.  

Edit: I had a look at the default config that you have provided and I see the the same thing.

**Comment by 0tho** [comment]
It was a simple but annoying bug. Thx for reporting
