### ISSUE TITLE
[Bug] Buckets do not render properly

### ISSUE THREAD

**Issue by Yulife** [0tho/CustomItems#23]
I am not sure if I have to create a custom texture for a fluid but in the end, my bucket does not render.
The bucket is on the [right](http://puu.sh/e65EN/3aee0d106a.jpg).
Using CustomThings .10

**Comment by 0tho** [comment]
You have to create a new texture for buckets in the items folder.
textureName_bucket.png

ps: the latest version of the mod is CustomItems 1.0.8

**Comment by Yulife** [comment]
I see ... thanks! Looking forward to 0.9 :D
