### ISSUE TITLE
[Suggestion] Prefix for Buckets

### ISSUE THREAD

**Issue by Yulife** [0tho/CustomItems#24]
I just noticed that the Custom Buckets, that automatically come when adding a fluid, are called like the fluid in the actual json, for example "Molten Zinc". Perhaps using "[JSON Fluid Name] Bucket" would be a more sensible solution ;)

**Comment by 0tho** [comment]
I will add a propertie so you can name the bucket as you want

**Comment by Yulife** [comment]
Awesome ;)
