### ISSUE TITLE
[Bug] Crop visual

### ISSUE THREAD

**Issue by Cyd007** [0tho/CustomItems#30]
Custom crops with the flower rendering config does not connect to farmland block. The follow is an example.

Custom Crop: 
https://dl.dropboxusercontent.com/u/68695308/custom%20items%20crash/2015-01-07/2015-01-07_15.43.59.png

Melon Crop:
https://dl.dropboxusercontent.com/u/68695308/custom%20items%20crash/2015-01-07/2015-01-07_15.44.34.png

Compare the two and you will see what I mean.

**Comment by 0tho** [comment]
Are you using the normal flower texture?

**Comment by Cyd007** [comment]
No it is a custom texture for the crop. Here it is in the final stage. 

![oxeye daisy4](https://cloud.githubusercontent.com/assets/10248908/5656138/ea443682-968c-11e4-8c38-5dd7962eaac9.png)

**Comment by 0tho** [comment]
This actually is not really a bug. The thing is that the crops render type renders 1px lower becuase of farmlands that if you see are 1px lower. Flowers should not be rendered above farmlands, so I will have to make a new custom render type for flowers that are planted on farmlands. 
I will fix this, but not right away

**Comment by Cyd007** [comment]
Okay, was not sure if it was or was not. It is not a that big of a deal, it is some I just some how notice.

Melons are render the same way as flowers and they have the 1px in farmland so you might want to start there for an idea on how to.
