### ISSUE TITLE
Armor Seems To Have A Minimum Reduction Value

### ISSUE THREAD

**Issue by earthcrafterman** [0tho/CustomItems#31]
I made 3 pieces of armor for use in my pack, but I fond something that puzzles me. I gave my shoes 0 reduction points and my leggings and tunic 1 and 2, respectively. (I'm using NBT Tags in MineTweaker to add a speed buff to players using the shoes to make up for the lack of reduction)

The problem is, all three show a armor value of 2 points (1 armor icon) Is this just a graphical thing, or are all of my armor items giving me the same reduction?

**Comment by Cyd007** [comment]
Would you mind posting the config file?

**Comment by 0tho** [comment]
Interesting. I will give a look at amors, but as Cyd said: Could you please post your config file? So I can better test what it is happening.

**Comment by earthcrafterman** [comment]
Sorry, didn't think I'd need to post it for this one:
http://pastebin.com/PhJqw905

**Comment by Cyd007** [comment]
No worries, its just to see how you set up the config for it and eleminate it as an issue.

**Comment by 0tho** [comment]
For some stupid reason I changed the propertie name to "reductionNum", I am now renaming it back to "reduction". So at 1.0.8, please use "reductionNum" as a workaround. 

Will be fixed at 1.0.9
