### ISSUE TITLE
[Idea] Server Configuration Download

### ISSUE THREAD

**Issue by Cyd007** [0tho/CustomItems#36]
Resources packs can be provided by a Minecraft server and be download directly from it without leaving the Minecraft client. 

I tested to see how the mod react when a configuration file was not present on the clients side. Example, test.json is in the server configuration folder but test.json was not on the client side configuration. The result sends a error message saying "Fatally missing block and items" and boots you from the server.

Now here is the idea... What if instead it prompts the user that they are required to have these configs for this server. Much like resource pack can be fore a server. And from there you can download it directly with going to a website to download it.

It might be a little more under taking to do something like this but I thought to throw the idea out there.

**Comment by 0tho** [comment]
Duplicated on BitBucket issue list
