### ISSUE TITLE
Seeds from Crops

### ISSUE THREAD

**Issue by jerjerje** [0tho/CustomItems#43]
I added a new crop, but it doesn't give me seeds back, when harvested.
Here is what I wrote:
{
"crops":
[
{"name": "Shard", "textureName":"shard_crop", "fruitName": "customitems:mixed_shard_essence", "renderType": "flower", "dropFromGrassChance": 0, "dropSeedWhenMature": true, "acceptBoneMeal": false, "minFruitDrop": 1, "maxFruitDrop": 1, "minSeedDrop": 1, "maxSeedDrop": 1, "eachExtraSeedDropChance": 0, "eachExtraFruitDropChance": 0, creativeTab = "Custom Items"}

]}
I don't know if I'm just stupid or if this is a bug. Could somebody help me?

**Comment by 0tho** [comment]
Just to be sure. What version of MM-CI are you using?

**Comment by jerjerje** [comment]
1.0.9

**Comment by 0tho** [comment]
With this config you should always get one seed.
I just fixed the json and added an item.
```
{
    "crops": [
        {
            "name": "Shard",
            "textureName": "shard_crop",
            "fruitName": "customitems:mixed_shard_essence",
            "renderType": "flower",
            "dropFromGrassChance": 0,
            "dropSeedWhenMature": true,
            "acceptBoneMeal": false,
            "minFruitDrop": 1,
            "maxFruitDrop": 1,
            "minSeedDrop": 1,
            "maxSeedDrop": 1,
            "eachExtraSeedDropChance": 0,
            "eachExtraFruitDropChance": 0,
            "creativeTab": "Custom Items"
        }
    ],

	  "items": [
        {
            "name": "Mixed Shard Essence",
            "textureName": "shard_essence",
            "creativeTab": "Custom Items",
            "maxStackSize": 7,
            "glows": true
        }
	  ]
}
