### ISSUE TITLE
CraftTweaker Support

### ISSUE THREAD

**Issue by guillaumearm** [0tho/CustomItems#63]
Hi, nice mod, I'm sure modpack makers love it.

It would be awesome to add [CraftTweaker](https://crafttweaker.readthedocs.io/en/latest/) integration, what do you think, is it possible technically ?

-------------

**Edit**: Maybe I'm asking the wrong thing, the correct question would be :

>  is there a way to get CustomItems work with CraftTweaker ?

**Comment by 0tho** [comment]
CustomItems is a very outdated Mod. 
It worked with minecraft 1.7.10, if the mod was updated to the current version of minecraft I bet there could be ways to integrate the mods

**Comment by guillaumearm** [comment]
Woops I didn't see that, sorry for the inconvenience.
