### ISSUE TITLE
Ore Generation Vein Size Issue

### ISSUE THREAD

**Issue by Shahelion** [0tho/CustomItems#65]
Looks like the Min and Max can't be the same, Max must be larger. I was trying to make it always generate only a single block, but it crashes when both are set to the same number (or when both are set to 1). I am on 1.7.10 if that matters.
https://gist.github.com/Shahelion/324d60742bd5e8a281f000ff38c0cd8f

**Comment by marcel0ll** [comment]
Hey @Shahelion I haven't made any changes to the mod in a long time.
There are some forks for the mod, not sure if those will help.

Feel free to fork it or open a PR

Unfortunately I can't justify updating the mod

**Comment by Shahelion** [comment]
Fair enough. And apparently, for veins of one block, the config needs to be min 1 and max 4 (in case anyone else finds this).
